/**
 * Wiki Viewer Generator
 *
 * Standalone module that generates wiki content as embedded HTML (for the /wiki
 * command, served via show-in-browser's HTTP server) and as a standalone wiki.js
 * data file (for the wiki update sync flow).
 *
 * No dependency on _embed.mjs or _content.js.
 */

import { readFile, readdir, stat } from "node:fs/promises";
import { existsSync } from "node:fs";
import { join, relative, basename, dirname } from "node:path";
import { createServer, type Server } from "node:http";
import { spawn } from "node:child_process";

const WIKI_DIR_NAME = "docs/wiki";
const SKIP_FILES = new Set(["log.md", "last_updated.md"]);
const SKIP_PREFIXES = ["changelog/"];

function wikiDir(cwd: string): string {
  return join(cwd, WIKI_DIR_NAME);
}

function shouldSkip(rel: string): boolean {
  if (SKIP_FILES.has(basename(rel))) return true;
  for (const pre of SKIP_PREFIXES) {
    if (rel.startsWith(pre)) return true;
  }
  return false;
}

/** Escape a string for use as a JavaScript template literal value. */
function jsEscape(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\${/g, "\\${")
    .replace(/<\/script>/gi, "<\\/script>");
}

/** Escape a string for use as a JavaScript string literal (double-quoted). */
function jsStr(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r");
}

// ---------------------------------------------------------------------------
// Wiki content scanner (shared between data + HTML generators)
// ---------------------------------------------------------------------------

interface WikiPage {
  path: string;
  label: string;
  group: string;
}

interface WikiData {
  content: Record<string, string>;
  pages: WikiPage[];
}

/** Read all markdown files in docs/wiki/, keyed by relative path. */
async function scanWikiContent(root: string): Promise<WikiData> {
  const content: Record<string, string> = {};
  const pages: WikiPage[] = [];

  async function walk(dir: string) {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const full = join(dir, e.name);
      if (e.isDirectory()) {
        await walk(full);
      } else if (e.name.endsWith(".md")) {
        const rel = relative(root, full).replace(/\\/g, "/");
        if (shouldSkip(rel)) continue;
        const text = await readFile(full, "utf8");
        content[rel] = text;
        pages.push({
          path: rel,
          label: inferLabel(text, rel),
          group: inferGroup(rel),
        });
      }
    }
  }

  if (existsSync(root)) {
    await walk(root);
  }

  pages.sort((a, b) => {
    if (a.path === "index.md") return -1;
    if (b.path === "index.md") return 1;
    if (a.group !== b.group) return a.group.localeCompare(b.group);
    return a.label.localeCompare(b.label);
  });

  return { content, pages };
}

function inferLabel(text: string, rel: string): string {
  const m = text.match(/^---\r?\n[\s\S]*?^title\s*:\s*(.+)$/m);
  if (m) return m[1].trim().replace(/^"|"$/g, "");
  const h1 = text.match(/^#\s+(.+)$/m);
  if (h1) return h1[1].trim();
  return basename(rel, ".md")
    .replace(/[-_]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function inferGroup(rel: string): string {
  const d = dirname(rel);
  if (d === "." || d === rel) return "";
  return d
    .split("/")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(" / ");
}

// ---------------------------------------------------------------------------
// wiki.js data generator
// ---------------------------------------------------------------------------

/**
 * Generate a wiki.js file content string containing WIKI_CONTENT and WIKI_PAGES.
 * Written to docs/wiki/wiki.js so the viewer HTML can load it via <script src>.
 */
export async function generateWikiDataJs(cwd: string): Promise<string> {
  const root = wikiDir(cwd);
  const { content, pages } = await scanWikiContent(root);

  const contentLines: string[] = [];
  for (const [k, v] of Object.entries(content)) {
    const escKey = jsStr(k);
    const escVal = jsEscape(v);
    contentLines.push(`  "${escKey}": \`${escVal}\`,`);
  }

  const pagesLines = pages.map(
    (p) => `  { path: "${jsStr(p.path)}", label: "${jsStr(p.label)}", group: "${jsStr(p.group)}" }`,
  );

  return [
    `// Generated by wiki viewer — content from docs/wiki/`,
    `var WIKI_CONTENT = {`,
    contentLines.join("\n"),
    `};`,
    ``,
    `var WIKI_PAGES = [`,
    pagesLines.join(",\n"),
    `];`,
    ``,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// wiki-viewer.html generator
// ---------------------------------------------------------------------------

/**
 * Generate a self-contained HTML wiki viewer with all content embedded inline.
 * Served via show-in-browser's HTTP server to avoid file:// script restrictions.
 */
export async function generateWikiViewerHtml(cwd: string): Promise<string> {
  const root = wikiDir(cwd);
  const { content, pages } = await scanWikiContent(root);

  const contentLines: string[] = [];
  for (const [k, v] of Object.entries(content)) {
    const escKey = jsStr(k);
    const escVal = jsEscape(v);
    contentLines.push(`  "${escKey}": \`${escVal}\`,`);
  }

  const pagesLines = pages.map(
    (p) => `    { path: "${jsStr(p.path)}", label: "${jsStr(p.label)}", group: "${jsStr(p.group)}" }`,
  );

  const projectName = basename(cwd);

const viewerIIFE = String.raw`(function(){
var a=document.getElementById("hljs-light"),d=document.getElementById("hljs-dark"),t=document.getElementById("themeToggle"),i=document.getElementById("themeIcon");
function g(){try{return localStorage.getItem("mdv-theme")||"auto"}catch(e){return"auto"}}
function l(o){var h=document.documentElement;h.setAttribute("data-theme",o);var k=o==="dark"||(o==="auto"&&window.matchMedia("(prefers-color-scheme: dark)").matches);h.classList.toggle("system-dark",o==="auto"&&window.matchMedia("(prefers-color-scheme: dark)").matches);a.disabled=k;d.disabled=!k;i.innerHTML=k?'<circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>':'<path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/>';t.title=k?"Switch to light mode":"Switch to dark mode"}
l(g());t.addEventListener("click",function(){var o=g(),h=o==="auto"?"light":o==="light"?"dark":"auto";try{localStorage.setItem("mdv-theme",h)}catch(e){}l(h)});window.matchMedia("(prefers-color-scheme: dark)").addEventListener("change",function(){if(g()==="auto")l("auto")});
var s=document.getElementById("sidebar"),sc=document.getElementById("sidebarScroll"),o=document.getElementById("output"),fn=document.getElementById("fileName"),bc=document.getElementById("breadcrumbCurrent"),bh=document.getElementById("breadcrumbHome"),bb=document.getElementById("backBtn"),fb=document.getElementById("fwdBtn"),hm=document.getElementById("homeBtn"),st=document.getElementById("sidebarToggle"),cs=document.getElementById("closeSidebarBtn"),cp="index.md",hs=[],hi=-1;
function es(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
function at(s){return String(s).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}
function rl(fp,ln){if(/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(ln))return null;if(ln.startsWith("#"))return null;var d=fp.lastIndexOf("/"),r=d>=0?fp.substring(0,d)+"/"+ln:ln;r=r.replace(/^\.\//,"");if(r.endsWith("/"))r+="index.md";if(!r.endsWith(".md"))r+="/index.md";r=r.replace(/\/\//g,"/");var p=r.split("/"),o=[];for(var i=0;i<p.length;i++){if(p[i]===".")continue;if(p[i]===".."&&o.length>0)o.pop();else if(p[i]!=="")o.push(p[i])}return o.join("/")}
function fm(p){return WIKI_CONTENT[p]?Promise.resolve(WIKI_CONTENT[p]):Promise.reject(new Error('Page "'+p+'" not found'))}
function rm(t,p){var c=t.replace(/^---[\s\S]*?---\s*/,""),h;if(typeof marked!=="undefined"){marked.setOptions({gfm:true,breaks:false});h=marked.parse(c)}else{h="<pre>"+es(c)+"</pre>"}o.innerHTML=h;if(typeof hljs!=="undefined"){o.querySelectorAll("pre code").forEach(function(b){hljs.highlightElement(b)})}o.querySelectorAll("a").forEach(function(a){var h=a.getAttribute("href");if(!h)return;if(/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(h)){a.setAttribute("target","_blank");a.setAttribute("rel","noopener noreferrer");return}if(h.startsWith("#")){a.addEventListener("click",function(e){e.preventDefault();var el=document.getElementById(h.substring(1));if(el)el.scrollIntoView({behavior:"smooth"})});return}a.addEventListener("click",function(e){e.preventDefault();var r=rl(p,h);if(r)nn(r)})});var h1=o.querySelector("h1");return h1?h1.textContent:p.replace(/\.md$/,"").split("/").pop()}
function nn(p,ph){if(ph===undefined)ph=true;p=p.replace(/^\.\//,"");if(p.endsWith("/"))p+="index.md";if(!p.endsWith(".md"))p+="/index.md";var pp=cp;cp=p;us(p);o.innerHTML='<div class="loading-state"><div class="spinner"></div><p>Loading '+es(p)+'...</p></div>';fm(p).then(function(t){var ti=rm(t,p);fn.textContent=ti;bc.textContent=ti;if(ph){hs=hs.slice(0,hi+1);hs.push(p);hi=hs.length-1;ub();try{window.history.pushState({path:p},"","#"+p)}catch(e){}}}).catch(function(e){o.innerHTML='<div class="error-banner">Could not load <strong>'+es(p)+"</strong>: "+es(e.message)+"</div>";fn.textContent="Error";bc.textContent="Error loading page";cp=pp;us(cp)})}
function us(p){sc.querySelectorAll(".tree-item").forEach(function(b){b.classList.toggle("active",b.getAttribute("data-path")===p)})}
function ub(){bb.disabled=hi<=0;fb.disabled=hi>=hs.length-1}
function gb(){if(hi>0){hi--;nn(hs[hi],false);ub();try{window.history.replaceState({path:hs[hi]},"","#"+hs[hi])}catch(e){}}}
function gf(){if(hi<hs.length-1){hi++;nn(hs[hi],false);ub();try{window.history.replaceState({path:hs[hi]},"","#"+hs[hi])}catch(e){}}}
function gh(){nn("index.md")}
function bt(){var g={};WIKI_PAGES.forEach(function(p){var gr=p.group||"";if(!g[gr])g[gr]=[];g[gr].push(p)});var gn=Object.keys(g).sort(function(a,b){if(a===""||a==="Architecture")return -1;if(b===""||b==="Architecture")return 1;return a.localeCompare(b)});var h="";gn.forEach(function(gr){if(gr)h+='<div class="tree-group-label">'+es(gr)+"</div>";g[gr].forEach(function(p){h+='<button class="tree-item'+(p.path===cp?" active":"")+'" data-path="'+at(p.path)+'"><svg class="tree-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z"/><polyline points="14 2 14 8 20 8"/></svg><span class="tree-label">'+es(p.label)+"</span></button>"})});sc.innerHTML=h;sc.querySelectorAll(".tree-item").forEach(function(b){b.addEventListener("click",function(){nn(b.getAttribute("data-path"));if(window.innerWidth<=768)s.classList.remove("show-mobile")})})}
bb.addEventListener("click",gb);fb.addEventListener("click",gf);hm.addEventListener("click",gh);bh.addEventListener("click",gh);st.addEventListener("click",function(){if(window.innerWidth<=768){s.classList.toggle("show-mobile")}else{s.style.display=s.style.display==="none"?"flex":"none"}});cs.addEventListener("click",function(){s.style.display="none"});window.addEventListener("popstate",function(e){if(e.state&&e.state.path){var idx=hs.indexOf(e.state.path);if(idx>=0){hi=idx;nn(e.state.path,false);ub()}else{nn(e.state.path)}}});
bt();var ip="index.md";if(window.location.hash){var hp=window.location.hash.substring(1);if(hp.endsWith(".md")||hp.endsWith("/")){ip=hp.replace(/^\.\//,"");if(ip.endsWith("/"))ip+="index.md"}}nn(ip,true);
})();`;

    return `<!doctype html>
<html lang="en" data-theme="auto">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${projectName} Wiki Viewer</title>
  <script src="https://cdn.jsdelivr.net/npm/marked/marked.min.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@11/styles/github.min.css" media="all" id="hljs-light" disabled />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/highlight.js@11/styles/github-dark.min.css" media="all" id="hljs-dark" disabled />
  <script src="https://cdn.jsdelivr.net/npm/highlight.js@11/highlight.min.js"></script>
  <style>
    :root {
      --bg: #ffffff; --surface: #f6f8fa; --surface-hover: #eaeef2;
      --border: #d0d7de; --text: #1f2328; --text-secondary: #656d76;
      --accent: #0969da; --accent-hover: #0550ae; --code-bg: #f6f8fa;
      --code-text: #1f2328; --pre-bg: #ffffff; --quote-border: #d0d7de;
      --quote-bg: #f6f8fa; --table-stripe: #f6f8fa; --link: #0969da;
      --hr: #d8dee4; --danger: #cf222e; --sidebar-bg: #f6f8fa;
      --sidebar-border: #d0d7de; --shadow: 0 1px 3px rgba(0,0,0,0.08);
      --sidebar-width: 260px; --toolbar-height: 48px;
    }
    html[data-theme="dark"], html[data-theme="auto"].system-dark {
      --bg: #0d1117; --surface: #161b22; --surface-hover: #1c2128;
      --border: #30363d; --text: #e6edf3; --text-secondary: #8b949e;
      --accent: #58a6ff; --accent-hover: #79c0ff; --code-bg: #161b22;
      --code-text: #e6edf3; --pre-bg: #0d1117; --quote-border: #30363d;
      --quote-bg: #161b22; --table-stripe: #161b22; --link: #58a6ff;
      --hr: #21262d; --danger: #f85149; --sidebar-bg: #161b22;
      --sidebar-border: #30363d; --shadow: 0 1px 3px rgba(0,0,0,0.3);
    }
    *,*::before,*::after { box-sizing: border-box; margin: 0; padding: 0; }
    html { -webkit-text-size-adjust: 100%; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif;
      font-size: 16px; line-height: 1.7; color: var(--text); background: var(--bg);
      min-height: 100vh; display: flex; flex-direction: column;
    }
    .app-layout { display: flex; flex: 1; min-height: 0; }
    .sidebar {
      width: var(--sidebar-width); flex-shrink: 0; background: var(--sidebar-bg);
      border-right: 1px solid var(--sidebar-border); display: flex; flex-direction: column;
      overflow: hidden; height: calc(100vh - var(--toolbar-height));
      position: sticky; top: var(--toolbar-height);
    }
    .sidebar-header {
      padding: 12px 16px; font-size: 13px; font-weight: 600;
      color: var(--text-secondary); text-transform: uppercase; letter-spacing: 0.04em;
      border-bottom: 1px solid var(--sidebar-border); flex-shrink: 0;
      display: flex; align-items: center; justify-content: space-between;
    }
    .sidebar-toggle-label { cursor: pointer; color: var(--accent); font-size: 11px; text-transform: none; letter-spacing: normal; font-weight: 500; }
    .sidebar-toggle-label:hover { text-decoration: underline; }
    .sidebar-scroll { flex: 1; overflow-y: auto; padding: 8px 0; }
    .sidebar-scroll::-webkit-scrollbar { width: 6px; }
    .sidebar-scroll::-webkit-scrollbar-track { background: transparent; }
    .sidebar-scroll::-webkit-scrollbar-thumb { background: var(--border); border-radius: 3px; }
    .tree-group-label {
      padding: 4px 16px 2px; font-size: 11px; font-weight: 600;
      color: var(--text-secondary); text-transform: uppercase; letter-spacing: 0.04em; margin-top: 4px;
    }
    .tree-item {
      display: flex; align-items: center; gap: 6px; padding: 5px 16px 5px 24px;
      font-size: 13px; color: var(--text); text-decoration: none; cursor: pointer;
      transition: background 0.12s; border: none; background: none; width: 100%;
      text-align: left; font-family: inherit; line-height: 1.4;
    }
    .tree-item:hover { background: var(--surface-hover); }
    .tree-item.active { background: var(--accent); color: #fff; font-weight: 500; }
    .tree-item .tree-icon { flex-shrink: 0; opacity: 0.6; }
    .tree-item.active .tree-icon { opacity: 1; }
    .tree-item .tree-label { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
    .main-area { flex: 1; min-width: 0; display: flex; flex-direction: column; overflow: hidden; }
    .breadcrumb {
      padding: 8px 24px; font-size: 13px; color: var(--text-secondary);
      border-bottom: 1px solid var(--border); background: var(--bg);
      display: flex; align-items: center; gap: 6px; flex-wrap: wrap; flex-shrink: 0;
    }
    .breadcrumb a { color: var(--link); text-decoration: none; cursor: pointer; }
    .breadcrumb a:hover { text-decoration: underline; }
    .breadcrumb .separator { color: var(--text-secondary); font-size: 12px; }
    .breadcrumb .current { color: var(--text); font-weight: 500; }
    .toolbar {
      height: var(--toolbar-height); flex-shrink: 0; background: var(--surface);
      border-bottom: 1px solid var(--border); padding: 0 16px;
      display: flex; align-items: center; gap: 10px; box-shadow: var(--shadow);
      position: sticky; top: 0; z-index: 30;
    }
    .toolbar .file-name {
      font-weight: 600; font-size: 13px; color: var(--text);
      overflow: hidden; text-overflow: ellipsis; white-space: nowrap; flex: 1; min-width: 0;
    }
    .toolbar button {
      background: var(--accent); color: #fff; border: none; border-radius: 6px;
      padding: 5px 12px; font-size: 12px; font-weight: 500; cursor: pointer;
      transition: background 0.15s; white-space: nowrap;
    }
    .toolbar button:hover { background: var(--accent-hover); }
    .toolbar .nav-btn {
      background: none; color: var(--text); border: 1px solid var(--border);
      padding: 4px 8px; display: flex; align-items: center; gap: 2px; font-size: 13px;
    }
    .toolbar .nav-btn:hover { background: var(--surface-hover); }
    .toolbar .nav-btn:disabled { opacity: 0.35; cursor: default; background: none; }
    .theme-toggle {
      background: none !important; color: var(--text) !important;
      border: 1px solid var(--border) !important; padding: 4px 7px !important;
      display: flex; align-items: center; gap: 4px; font-size: 13px !important;
      border-radius: 6px; cursor: pointer; flex-shrink: 0;
    }
    .theme-toggle:hover { background: var(--surface-hover) !important; }
    .theme-toggle svg { width: 15px; height: 15px; }
    .container {
      flex: 1; overflow-y: auto; padding: 32px 40px 80px;
      max-width: 960px; margin: 0 auto; width: 100%;
    }
    .container::-webkit-scrollbar { width: 8px; }
    .container::-webkit-scrollbar-track { background: transparent; }
    .container::-webkit-scrollbar-thumb { background: var(--border); border-radius: 4px; }
    .md-body h1,.md-body h2,.md-body h3,.md-body h4,.md-body h5,.md-body h6 { margin-top: 24px; margin-bottom: 16px; font-weight: 600; line-height: 1.25; }
    .md-body h1 { font-size: 2em; padding-bottom: 0.3em; border-bottom: 1px solid var(--hr); }
    .md-body h2 { font-size: 1.5em; padding-bottom: 0.3em; border-bottom: 1px solid var(--hr); }
    .md-body h3 { font-size: 1.25em; }
    .md-body h4 { font-size: 1em; }
    .md-body h5 { font-size: 0.875em; }
    .md-body h6 { font-size: 0.85em; color: var(--text-secondary); }
    .md-body p { margin-bottom: 16px; }
    .md-body a { color: var(--link); text-decoration: none; cursor: pointer; }
    .md-body a:hover { text-decoration: underline; }
    .md-body strong { font-weight: 600; }
    .md-body del { text-decoration: line-through; color: var(--text-secondary); }
    .md-body ul,.md-body ol { margin-bottom: 16px; padding-left: 2em; }
    .md-body li { margin-bottom: 4px; }
    .md-body li > p { margin-bottom: 8px; }
    .md-body blockquote { margin: 0 0 16px; padding: 8px 16px; border-left: 4px solid var(--quote-border); background: var(--quote-bg); color: var(--text-secondary); }
    .md-body code { font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace; font-size: 85%; background: var(--code-bg); padding: 0.2em 0.4em; border-radius: 6px; color: var(--code-text); }
    .md-body pre { margin-bottom: 16px; padding: 16px; overflow: auto; border-radius: 8px; background: var(--pre-bg); line-height: 1.5; }
    .md-body pre code { display: block; background: none; padding: 0; border-radius: 0; font-size: 13px; white-space: pre; word-wrap: normal; }
    .md-body table { border-collapse: collapse; width: 100%; margin-bottom: 16px; overflow: auto; }
    .md-body th,.md-body td { border: 1px solid var(--border); padding: 8px 13px; }
    .md-body th { font-weight: 600; background: var(--surface); }
    .md-body tr:nth-child(even) td { background: var(--table-stripe); }
    .md-body hr { border: none; border-top: 2px solid var(--hr); margin: 24px 0; }
    .md-body img { max-width: 100%; border-radius: 8px; margin: 8px 0; }
    .md-body input[type="checkbox"] { margin-right: 6px; accent-color: var(--accent); }
    .loading-state { display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 80px 20px; gap: 20px; }
    .loading-state .spinner { width: 36px; height: 36px; border: 3px solid var(--border); border-top: 3px solid var(--accent); border-radius: 50%; animation: spin .8s linear infinite; }
    @keyframes spin { to { transform: rotate(360deg); } }
    .loading-state p { color: var(--text-secondary); font-size: 15px; }
    .error-banner { background: #ffebe9; border: 1px solid var(--danger); color: var(--danger); padding: 12px 16px; border-radius: 8px; margin-bottom: 20px; font-size: 14px; }
    html[data-theme="dark"] .error-banner, html[data-theme="auto"].system-dark .error-banner { background: #3d1214; }
    @media (max-width: 768px) {
      .sidebar { display: none; }
      .sidebar.show-mobile { display: flex; position: fixed; inset: 0; z-index: 50; width: 100%; height: 100%; top: var(--toolbar-height); }
      .container { padding: 20px 16px 60px; }
      .breadcrumb { padding: 6px 16px; font-size: 12px; }
    }
  </style>
</head>
<body>
  <div class="toolbar" id="toolbar">
    <button class="nav-btn" id="backBtn" title="Back" disabled>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 8L2 12L6 16"/><path d="M2 12H22"/></svg>
    </button>
    <button class="nav-btn" id="fwdBtn" title="Forward" disabled>
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8L22 12L18 16"/><path d="M2 12H22"/></svg>
    </button>
    <span class="file-name" id="fileName">${projectName} Wiki</span>
    <button id="sidebarToggle" title="Toggle sidebar">&#9776;</button>
    <button id="homeBtn">Home</button>
    <button class="theme-toggle" id="themeToggle" title="Toggle theme">
      <svg id="themeIcon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/>
        <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/>
        <line x1="1" y1="12" x2="3" y2="12"/><line x21="21" y1="12" x2="23" y2="12"/>
        <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
      </svg>
    </button>
  </div>

  <div class="app-layout">
    <nav class="sidebar" id="sidebar">
      <div class="sidebar-header">
        <span>Wiki Pages</span>
        <span class="sidebar-toggle-label" id="closeSidebarBtn">&#215; close</span>
      </div>
      <div class="sidebar-scroll" id="sidebarScroll"></div>
    </nav>

    <div class="main-area">
      <div class="breadcrumb" id="breadcrumb">
        <a id="breadcrumbHome">Wiki</a>
        <span class="separator">/</span>
        <span class="current" id="breadcrumbCurrent">loading...</span>
      </div>
      <div class="container" id="container">
        <article class="md-body" id="output">
          <div class="loading-state"><div class="spinner"></div><p>Loading wiki...</p></div>
        </article>
      </div>
    </div>
  </div>

  <script>
var WIKI_CONTENT = {
${contentLines.join("\n")}
};
var WIKI_PAGES = [
${pagesLines.join(",\n")}
];
${viewerIIFE}
  </script>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Local HTTP server — serves the wiki viewer in the browser
// ---------------------------------------------------------------------------

const wikiServers = new Map<string, { server: Server; port: number }>();

function openBrowser(url: string): void {
  const cmd =
    process.platform === "win32"
      ? `start "" "${url}"`
      : process.platform === "darwin"
        ? `open "${url}"`
        : `xdg-open "${url}"`;
  // Fire-and-forget — spawn detached so pi isn't blocked
  spawn(cmd, [], { shell: true, detached: true, stdio: "ignore" }).unref();
}

/**
 * Start a local HTTP server on 127.0.0.1 that serves the wiki viewer.
 * Reuses any existing server for the same cwd (just opens the URL again).
 * Returns the URL to open.
 */
export async function serveWikiViewer(cwd: string): Promise<string> {
  // Already running for this project? Just return its URL.
  const existing = wikiServers.get(cwd);
  if (existing) {
    const url = `http://127.0.0.1:${existing.port}/`;
    openBrowser(url);
    return url;
  }

  const html = await generateWikiViewerHtml(cwd);

  const server = createServer(async (_req, res) => {
    // ponytail: regenerate on every request so new wiki content appears immediately
    const fresh = await generateWikiViewerHtml(cwd);
    res.writeHead(200, { "Content-Type": "text/html; charset=utf-8" });
    res.end(fresh);
  });

  const port = await new Promise<number>((resolve, reject) => {
    server.listen(0, "127.0.0.1", () => {
      const addr = server.address();
      if (addr && typeof addr === "object") resolve(addr.port);
      else reject(new Error("Failed to get port"));
    });
    server.on("error", reject);
  });

  wikiServers.set(cwd, { server, port });
  const url = `http://127.0.0.1:${port}/`;
  openBrowser(url);
  return url;
}

/** Shut down the wiki server for a given project (call on session_shutdown). */
export function shutdownWikiServer(cwd: string): void {
  const entry = wikiServers.get(cwd);
  if (entry) {
    entry.server.close();
    wikiServers.delete(cwd);
  }
}

/** Shut down all wiki servers (call on session_shutdown with no cwd). */
export function shutdownAllWikiServers(): void {
  for (const [key, { server }] of wikiServers) {
    server.close();
  }
  wikiServers.clear();
}
